Demo schedule
SDP-group22/Helio-app pull request #78
Opened 2021-02-24 15:27 UTC by Jeremy-hao

Tomorrow I will fill up the XML page. Please give me some images about what kinds of XML page we want. Currently, I have no idea about what this page should look like.

2021-02-24 23:13 UTC, nout-kleef commented
I think the following is a nice example for an overview (left) and time selection (right):
![preview](https://user-images.githubusercontent.com/30589554/109078518-5cbeb800-76f5-11eb-8478-56865176a4ee.png)

The following image is another example of how the overview of a few schedules might look:
![6508b9a6b4b1a20c7799e9e06e83703d](https://user-images.githubusercontent.com/30589554/109078717-b8894100-76f5-11eb-8d7f-056e62f01a4c.jpg)


Of course, we will need to include whether we want the blind to either open or close at that time, so these are not perfect examples.

2021-02-25 12:05 UTC, adamb56789 commented
Instead or as well as open or close you could make it so you can choose which level you want to move to. Maybe you could use the same slider that is used in the control part ([layout file](https://github.com/SDP-group22/Helio-app/blob/main/app/src/main/res/layout/control_list_item.xml), [class](https://github.com/SDP-group22/Helio-app/blob/main/app/src/main/java/com/helio/app/ui/control/ControlRecViewAdapter.java)).

2021-02-26 04:07 UTC, Jeremy-hao commented
The API of time picker didn't work. I wrote an annotation in the FragmentTimerActivity.

2021-02-26 11:04 UTC, adamb56789 requested changes
I think the instructions were a bit unclear. I made some boilerplate and template code to make the requirements for the scheduling pages more clear. Some additional recommendations, which are repeated in comments in the relevant files:
### The list items of the schedules recycler view
- [] The name if there is one
- [] Some sort of visual indicator which displays the target level of the motor
- [] An indicator of which days it is active
- [] A switch (https://material.io/components/switches) which controls whether this schedule is on or off
### The settings page for a schedule
- [] The time, which opens a time picker (https://material.io/components/time-pickers) when clicked on which displays the target level of the motor
- [] The days of the week, as 7 circles containing the letters MTWTFSS which when pressed become highlighted to control the days that it gets activated
- [] A text field (https://material.io/components/text-fields) to set the name
- [] A slider like the ones in control_list_item to set the target level
- [] Some sort of way to select which blinds this schedule applies to, such as using a drop down menu and checkboxes (https://material.io/components/checkboxes)

Please also try to make your commit messages more descriptive, also try to split up your commits into smaller chunks. For example "Added time picker for schedules".
Try to connect it to the backend if you can, I've left in some code copied from the blinds code that should get that started. You may have to make a couple of new methods in UserDataViewModel.

2021-02-26 11:13 UTC, adamb56789 commented on app/src/main/res/layout/schedule_list_item.xml
> +            android:id="@+id/blindIcon"
I forgot to change the ID here, change it s=to something sensible.

2021-03-07 06:16 UTC, Jeremy-hao commented
Currently, I still didn't finish the days of week UI and its function. I will finish it before today.

2021-03-09 12:08 UTC, adamb56789 reviewed
I'll take over finishing this ticket, can you work on the sensors?

2021-03-09 13:22 UTC, Jeremy-hao commented
Yes, of course

2021-03-12 17:08 UTC, closed without merging