Theme switching
SDP-group22/Helio-app pull request #96
Opened 2021-03-08 19:49 UTC by nout-kleef

Summary of changes:

- I refactored the "hub connection" fragment into a more general "settings" fragment. I added a dropdown here that allows the user to select their desired app theme.
- Upon selection, the new theme is stored using `SharedPreferences`, after which the `MainActivity` is reloaded (unfortunately this is the only way to update the app's theme at runtime)
- Upon starting the `MainActivity`, we fetch the desired theme from `SharedPreferences` to find out which theme we should use.

This adds everything that we need to add as many themes as we like:

1. Add styling to `res/values/styles.xml` (which replaces individual files for every theme)
2. Reference this new style from `res/values/styles.xml` in `theme_options` using a sensible name.
3. Add this same name to the switch statement in `getTheme(AppTheme theme)` in `MainActivity`

I'm not too happy about the looks of the dropdown, but all the functionality is there. @Jeremy-hao maybe we can make the settings fragment look nicer when you have time after Demo 3?

Closes #62

2021-03-08 20:57 UTC, adamb56789 requested changes
I see what you mean about the dropdown menu, we should probably use a [menu](https://material.io/components/menus) instead though that can be done later. The other issue that the night mode background is still white. Does that have to be controlled by the user at the android level? I tried just changing `android:windowBackground` to black but that also broke other things (you'll see). I think it needs a bit more work to make sure the night mode looks good.
![image](https://user-images.githubusercontent.com/17644409/110380597-3e8b7d00-8050-11eb-8be5-1cba80b57ecb.png)

2021-03-09 18:03 UTC, nout-kleef commented
closes #89

2021-03-10 11:09 UTC, Jeremy-hao approved these changes

2021-03-10 11:20 UTC, Jeremy-hao commented
I think we can discuss the detailed dropdown menu tomorrow or later?

2021-03-10 11:21 UTC, merged